# Generated by Django 4.2 on 2024-07-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_mailing_end_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("can_edit_status", "can edit status")],
                "verbose_name": "настройка рассылки",
                "verbose_name_plural": "настройки рассылок",
            },
        ),
    ]
