# Generated by Django 4.2 on 2024-07-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_mailing_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="next_send_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время следующей отправки"
            ),
        ),
    ]
